### ISSUE TITLE
Error with 3.0.0-pre.11

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook-html#1]
Hi,

Building with the new pre-release throws an error:

```
TypeError: Object function () {
        var args = _.toArray(arguments);
        args[0] = toHTML(args[0]);

        return fn.apply(null, args);
    } has no method 'prepare'
```

**Comment by SamyPesse** [comment]
When is this error happening? Our unit tests for GitBook on Mac/Linux are all passing.

BTW: `gitbook-html` is not a module that can be used directly, it's a dependency of `gitbook-markdown` and `gitbook-asciidoc`.

**Comment by nagim** [comment]
Building through the website (haven't tried CLI). The files built
successfully before with 2.6.7. and 3.0.0-pre.9.
I only created the issue there, because the way I see, the referenced code
comes from the gtibook-html.

Similar error message appeared when using the gitbook-plugin-scripts.

Cheers,
Imre

2016-05-03 12:42 GMT+02:00 Samy Pessé notifications@github.com:

**Comment by SamyPesse** [comment]
Closed in favor of https://github.com/GitbookIO/gitbook/issues/1263
